### ISSUE TITLE
Resizing window so that split conflicts with min-width makes sash overlap child view

### ISSUE THREAD

**Issue by BryanCrotaz** [BryanHunt/ember-split-view#14]

**Comment by Twinkletoes** [comment]
Actually only a problem if both panes have a min-width, and the total is less than the window width. Currently the panes overlap in this case - would be nice to find a more aesthetic way to fail.

**Comment by michael-k** [comment]
Maybe give the container a `min-width` and an `overflow`?

Alternatively you could drop the split and – if split is vertical – put the left one on top of the right one.

I think it depends on the use case which solution is best.

**Comment by Twinkletoes** [comment]
if it depends on use case then we should do it in css so user can override behaviour. So add an "overflow" class to the view if the child panes can't be fitted into it?

Default could be to go with overflow:scroll. Alternatively, we could just have overflow:scroll on the whole time, as we're ensuring that there's no overflow by resizing everything. The only overflow we get is when the children won't fit do to min-widths.

**Comment by BryanCrotaz** [comment]
I'm wondering whether split should be measured in pixels, not percent. Then we wouldn't have a conflict as the browser resizes.

**Comment by BryanHunt** [comment]
The components were originally coded using pixels.  It was rather complicated and had its own problems.  If you want to try it, go for it.

**Comment by BryanCrotaz** [comment]
What sorts of problems did you hit? What do I need to avoid in a new design?

**Comment by BryanCrotaz** [comment]
My major problem is in trying to code a min width for a sidebar. Because the split is in % and the minwidth is in css in pixels, horrible things happen when the split is too narrow.

**Comment by BryanHunt** [comment]
I don't remember the exact problems, but they were the reason the code was converted to use % by a contributor.

**Comment by BryanCrotaz** [comment]
ok, I'll play around and see if I can do any better. No promises!

**Comment by BryanHunt** [comment]
BTW, There is now an ember-resize addon that may help.  https://github.com/mike-north/ember-resize

**Comment by BryanCrotaz** [comment]
:) was using it last week. It was going to be my first port of call.

**Comment by BryanCrotaz** [comment]
Made a start, and it's going well.  Seems cleaner too. I've also fixed all the deprecations and the csp stuff.

A few bugs still to iron out, but the core feels good.

https://github.com/BryanCrotaz/ember-split-view/commit/2aa3a857f4ed3d704c9034ca9bc7a3044a9b9501

**Comment by BryanCrotaz** [comment]
Fixed it.

**Comment by BryanCrotaz** [comment]
Fixed by PR #29
