### ISSUE TITLE
Update to latest Ember-cli to avoid old bug

### ISSUE THREAD

**Issue by Twinkletoes** [BryanHunt/ember-split-view#16]
I'm hitting this bug when running the demo app

https://github.com/ember-cli/ember-cli/issues/2150

It's been fixed, so best to upgrade ember-cli in your demo app and in the addon

**Comment by BryanHunt** [comment]
Hmmm, I can run the demo app just fine.

ember-cli certainly needs to be updated, so I'll go ahead and do that

**Comment by BryanHunt** [comment]
Done
