### ISSUE TITLE
Add support for EmberJS 2.0

### ISSUE THREAD

**Issue by BryanHunt** [BryanHunt/ember-split-view#30]
Update the code to support EmberJS 2.0.

**Comment by BryanHunt** [comment]
I updated the dependencies to Ember 2.1.0, and the dummy app seems to work just fine.  I'll probably wait till ember-cli 2.0 for the final changes.

**Comment by BryanCrotaz** [comment]
Great!

**Comment by BryanHunt** [comment]
The code is working fine with Ember 2.x

**Comment by ArtemAlagizov** [comment]
@BryanHunt, could you please add support for Ember 2.9.x, it throws the following error:

"Assertion Failed: You must use Ember.set() to set the `parentView` property (of <app@component:split-child::ember1057>) to `<app@component:split-view::ember1049>`."

Thanks in advance!

**Comment by BryanHunt** [comment]
@ArtemAlagizov I believe PR #38 will fix this.

**Comment by ArtemAlagizov** [comment]
@BryanHunt, thanks, mate!
Is it ready to be installed?
I have tried installing the pull-request and that didn't work for me at all, even for ember 2.7.3: the basic example below didn't render correctly - split-sash is horizontal, although it is supposed to be vertical and when I try to move it - I get "Error: Property set failed: object in path "parent" could not be found or was destroyed".

That's the code I used: 
`{{#split-view isVertical=true}}
  {{#split-child}}
    Content of the left view here.
  {{/split-child}}
  {{split-sash}}
  {{#split-child}}
    Content of the right view here.
  {{/split-child}}
{{/split-view}}`

**Comment by BryanHunt** [comment]
I believe the PR has an API (template) change.  Have a look at the dummy example in the PR

**Comment by ArtemAlagizov** [comment]
nice one! everything works for Ember 2.9.1
