### ISSUE TITLE
Nested split view doesn't handle window resize correctly

### ISSUE THREAD

**Issue by meggers** [BryanHunt/ember-split-view#33]
I've got this setup:

```
  {{#split-view isVertical=true splitPosition=initialVerticalSplit}}
    {{#split-child}}
      {{#split-view isVertical=false splitPosition=initialHorizontalSplit }}
        {{#split-child}}
          <div></div>
        {{/split-child}}
        {{split-sash}}
        {{#split-child}}
          <div></div>
        {{/split-child}}
      {{/split-view}}
    {{/split-child}}
    {{split-sash}}
    {{#split-child}}
      <div></div>
    {{/split-child}}
  {{/split-view}}
```

So, basically two columns, with the first having two rows. When I resize the window horizontally (or diagonally), all panes get resized correctly. However, when I resize vertically, the bottom of the top row on the left column moves too far up, becoming separated from the sash and bottom row which stay fixed to the bottom of the window.

When I then resize the window horizontally, the bottom of the top row on the left column snaps back into position at the top of the sash.

Has anyone had this issue? I tried making a JSBin but am not sure how to add ember-split-view as a component.

**Comment by BryanHunt** [comment]
I'll try to look at this next week.

**Comment by meggers** [comment]
I just found the issue. For some reason, my top level split-view didn't have a height, so its height never changed (always zero) and any observers watching its height never got triggered. Not sure the best way to fix it, but I reopen the split view already to add a service to it so I'll just add a full-height class there.

Thanks for this component! It's very useful.

**Comment by BryanHunt** [comment]
:+1:
