### ISSUE TITLE
Doesn't lay out correctly in container with position:absolute parent

### ISSUE THREAD

**Issue by Twinkletoes** [BryanHunt/ember-split-view#8]

**Comment by BryanHunt** [comment]
Could you submit as a PR?

**Comment by Twinkletoes** [comment]
Working on exactly that now

**Comment by BryanHunt** [comment]
Awesome.  I will try to get these merged over lunch or later tonight.  If you have time to update the changelog, that would be appreciated.  If not, I'll take care of it.

**Comment by Twinkletoes** [comment]
Run some manual tests too - I've tested in an absolute container that fills the page (which was broken), with two vertical panes.

Haven't tested:
Layout with nested panes
Layout with horizontal
Layout into a position:relative container

**Comment by Twinkletoes** [comment]
I've fixed the problem with the simple views - silly me, I'd added the css classes in my test app, not in the components. Working on the composite views now.

**Comment by Twinkletoes** [comment]
Done

**Comment by BryanHunt** [comment]
So can we close this then?

**Comment by Twinkletoes** [comment]
Fixed by PR #17

**Comment by BryanHunt** [comment]
Fixed
